# -*- coding: utf-8 -*-
"""Demo registry with enrolled faces — synthetic people, real pipeline.

`suspect_seed.py` deliberately ships records with no face template, because a
template can only honestly come from a photo somebody enrolled. That is the
right default for a fresh install, and it also means the identification half of
the tool has nothing to demonstrate until an analyst uploads something. This
script is that analyst, run from the terminal.

Every face here is generated by StyleGAN (thispersondoesnotexist.com) and
depicts **nobody**. That is not a detail — this registry attaches criminal
records, charge sheets and risk levels to a face, and a confirmed match asserts
that record against whoever is standing in front of the camera. Pointing that
machinery at a photograph of a real person is how a demo turns into an
accusation, so the images are synthetic by construction and every row created
here says so in its notes.

What it does, in two passes:

  1. the four `source="seed"` records get the reference photo and the physical
     descriptors they were always missing (height, occupation, marks), which is
     what makes them matchable at all
  2. six new `source="demo_seed"` records are created across the record types,
     each fully classified — height, age, occupation, charges, convictions,
     case IDs, jurisdiction — so the registry exercises ranking, the filters
     and the ambiguous-match path rather than returning one row

Idempotent: a record that already carries a template is left alone, so re-runs
are free. Photos are cached under `backend/.demo_faces/` and only fetched once.

    python -m app.data.face_demo_seed              # seed / top up
    python -m app.data.face_demo_seed --reset      # remove what it created
    python -m app.data.face_demo_seed --offline    # cache only, no network

Writes through the ORM rather than the HTTP API on purpose: `POST /api/faces/
enroll` takes only a handful of Form fields and cannot set height, occupation,
age, gender or charges at all, so the API route could not produce these records.
"""
from __future__ import annotations

import argparse
import hashlib
import logging
import time
from pathlib import Path

from sqlmodel import col, select

from app.config import BASE_DIR
from app.database import session_scope
from app.models import Suspect
from app.models.models import utcnow
from app.osint import face_db
from app.osint.face_detect import encode_reference

log = logging.getLogger("sentinel.face_demo_seed")

#: Marks the rows this script owns, so --reset can delete its own work and
#: nothing else. Records enrolled by a real analyst are source="analyst" and
#: are never touched here.
DEMO_SOURCE = "demo_seed"

#: StyleGAN-generated portraits, 1024x1024, a different person per request.
#: The Referer is required — a bare request gets a 404 HTML page.
_FACE_URL = "https://thispersondoesnotexist.com/random-person.jpeg"
_REFERER = "https://thispersondoesnotexist.com/"
_CACHE_DIR = Path(BASE_DIR) / ".demo_faces"
#: Politeness gap between fetches from a free single-purpose service.
_FETCH_GAP = 1.5

_SYNTHETIC_NOTE = (
    "Reference photo is a StyleGAN-generated face and depicts no real person. "
    "Enrolled by app/data/face_demo_seed.py so the identification pipeline is "
    "demonstrable end to end.")

_DEMO_NOTE = ("SYNTHETIC DEMO RECORD — not a real person. " + _SYNTHETIC_NOTE)


# ── the descriptors the four seeded records never had ───────────────────────
#
# Keyed by full_name because that is what suspect_seed.py writes and the ids
# are generated per install.

_AUGMENT: dict[str, dict] = {
    "Ravi Bhai Solanki": {
        "height_cm": 178, "occupation": "Auto-rickshaw driver",
        "identifying_marks": "Scar on left forearm; chipped upper-left incisor",
    },
    "Imran Shaikh": {
        "height_cm": 172, "occupation": "Mobile repair technician",
        "identifying_marks": "Burn mark on right hand",
    },
    "Kiran Patel": {
        "height_cm": 169, "occupation": "Printing press owner",
        "identifying_marks": "Spectacles; greying temples",
    },
    "Meera Joshi": {
        "height_cm": 158, "occupation": "BSc student",
        "identifying_marks": "Mole below left eye",
    },
}


# ── six new records, fully classified ───────────────────────────────────────

_NEW: list[dict] = [
    {
        "full_name": "Dinesh Chauhan",
        "aliases": ["Dinu", "D.C."],
        "record_type": "wanted",
        "risk_level": "critical",
        "status": "at_large",
        "jurisdiction": "Varachha Police Station, Surat",
        "last_known_location": "Surat",
        "wanted_since": "2026-07-02",
        "convictions": 2,
        "case_ids": ["FIR 0229/2026 — Varachha PS", "FIR 0401/2024 — Katargam PS"],
        "charges": [
            {"section": "IPC 153A", "description": "Promoting enmity between groups",
             "status": "charged", "date": "2026-07-02"},
            {"section": "IPC 120B", "description": "Criminal conspiracy",
             "status": "charged", "date": "2026-07-02"},
            {"section": "IT Act 66F", "description": "Cyber terrorism — coordinated rumor campaign",
             "status": "convicted", "date": "2024-09-11"},
        ],
        "gender": "male", "age": 37, "height_cm": 181, "nationality": "Indian",
        "occupation": "Textile market broker",
        "identifying_marks": "Tattoo of a trident on right shoulder",
    },
    {
        "full_name": "Sanjay Thakor",
        "aliases": ["Sanju"],
        "record_type": "wanted",
        "risk_level": "high",
        "status": "at_large",
        "jurisdiction": "Naroda Police Station, Ahmedabad",
        "last_known_location": "Ahmedabad",
        "wanted_since": "2026-03-21",
        "convictions": 0,
        "case_ids": ["FIR 0118/2026 — Naroda PS"],
        "charges": [
            {"section": "IPC 505(1)(b)", "description": "Statements conducing to public mischief",
             "status": "charged", "date": "2026-03-21"},
            {"section": "IPC 143", "description": "Member of an unlawful assembly",
             "status": "under trial", "date": "2026-03-21"},
        ],
        "gender": "male", "age": 26, "height_cm": 174, "nationality": "Indian",
        "occupation": "Delivery rider",
        "identifying_marks": "Healed fracture, left wrist",
    },
    {
        "full_name": "Firoz Ansari",
        "aliases": ["Firu"],
        "record_type": "criminal",
        "risk_level": "high",
        "status": "in_custody",
        "jurisdiction": "Cyber Cell, Vadodara",
        "last_known_location": "Vadodara",
        "convictions": 3,
        "case_ids": ["FIR 0066/2023 — Cyber Cell Vadodara",
                     "FIR 0197/2025 — Sayajigunj PS"],
        "charges": [
            {"section": "IPC 469", "description": "Forgery to harm reputation",
             "status": "convicted", "date": "2023-08-14"},
            {"section": "IPC 500", "description": "Defamation",
             "status": "convicted", "date": "2023-08-14"},
            {"section": "IT Act 66D", "description": "Cheating by personation using a computer",
             "status": "convicted", "date": "2025-06-30"},
            {"section": "IT Act 67", "description": "Publishing obscene material electronically",
             "status": "under trial", "date": "2025-06-30"},
        ],
        "gender": "male", "age": 31, "height_cm": 167, "nationality": "Indian",
        "occupation": "Freelance graphic designer",
        "identifying_marks": "Surgical scar above right eyebrow",
    },
    {
        "full_name": "Bhavesh Rathod",
        "aliases": [],
        "record_type": "criminal",
        "risk_level": "medium",
        "status": "on_bail",
        "jurisdiction": "Gondal Road PS, Rajkot",
        "last_known_location": "Rajkot",
        "convictions": 1,
        "case_ids": ["FIR 0052/2025 — Gondal Road PS"],
        "charges": [
            {"section": "IPC 295A", "description": "Acts intended to outrage religious feelings",
             "status": "convicted", "date": "2025-02-18"},
        ],
        "gender": "male", "age": 44, "height_cm": 170, "nationality": "Indian",
        "occupation": "Shopkeeper — electrical goods",
        "identifying_marks": "Partial hearing loss, left ear",
    },
    {
        "full_name": "Nilesh Vaghela",
        "aliases": ["Nil"],
        "record_type": "person_of_interest",
        "risk_level": "medium",
        "status": "under_investigation",
        "jurisdiction": "SOG, Surat",
        "last_known_location": "Surat",
        "convictions": 0,
        "case_ids": ["Enquiry 47/2026 — SOG Surat"],
        "charges": [],
        "gender": "male", "age": 29, "height_cm": 176, "nationality": "Indian",
        "occupation": "Social media page administrator",
        "identifying_marks": "None recorded",
        "notes_extra": "Named in an ongoing enquiry into amplification of an "
                       "unverified child-kidnapping rumour. No charges filed.",
    },
    {
        "full_name": "Anita Desai",
        "aliases": [],
        "record_type": "missing",
        "risk_level": "low",
        "status": "under_investigation",
        "jurisdiction": "Karelibaug PS, Vadodara",
        "last_known_location": "Vadodara",
        "convictions": 0,
        "case_ids": ["MP 0071/2026 — Karelibaug PS"],
        "charges": [],
        "gender": "female", "age": 19, "height_cm": 161, "nationality": "Indian",
        "occupation": "Diploma student — nursing",
        "identifying_marks": "Birthmark on right forearm",
        "notes_extra": "Missing-person report. Registry entry exists so any face "
                       "match in circulating media routes to the investigating officer.",
    },
]


# ── photo supply ────────────────────────────────────────────────────────────

def _cached_faces() -> list[Path]:
    if not _CACHE_DIR.exists():
        return []
    return sorted(p for p in _CACHE_DIR.iterdir()
                  if p.suffix.lower() in {".jpg", ".jpeg", ".png"})


def _fetch_face() -> Path | None:
    """Pull one generated portrait into the cache. Returns its path, or None.

    Named by content hash so an unlucky duplicate from the generator does not
    occupy two cache slots and two enrolment attempts.
    """
    import httpx

    try:
        response = httpx.get(_FACE_URL, headers={"Referer": _REFERER},
                             timeout=30.0, follow_redirects=True)
    except Exception as exc:
        log.warning("could not reach the face generator: %s", exc)
        return None
    ctype = response.headers.get("content-type", "")
    if response.status_code != 200 or not ctype.startswith("image/"):
        log.warning("face generator answered HTTP %s (%s)",
                    response.status_code, ctype or "no content type")
        return None

    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(response.content).hexdigest()[:16]
    path = _CACHE_DIR / f"{digest}.jpg"
    if not path.exists():
        path.write_bytes(response.content)
    return path


class FaceSupply:
    """Hands out one usable, not-yet-used portrait at a time.

    Encoding can legitimately fail on a generated image (an unusual crop, a
    profile view), so a caller that simply took the next file would leave a
    record unenrolled for no reason. This retries with a fresh face instead,
    and falls back to the cache when the network is unavailable.
    """

    def __init__(self, *, offline: bool = False) -> None:
        self._offline = offline
        self._pool = _cached_faces()
        self._used: set[Path] = set()
        self._last_fetch = 0.0

    def _next_path(self) -> Path | None:
        for path in self._pool:
            if path not in self._used:
                return path
        if self._offline:
            return None
        gap = _FETCH_GAP - (time.monotonic() - self._last_fetch)
        if gap > 0:
            time.sleep(gap)
        self._last_fetch = time.monotonic()
        path = _fetch_face()
        if path is None:
            return None
        if path not in self._pool:
            self._pool.append(path)
        return None if path in self._used else path

    def take(self, *, attempts: int = 4) -> tuple[object, dict] | None:
        """Returns (PIL image, encode_reference result) or None."""
        from PIL import Image

        for _ in range(attempts):
            path = self._next_path()
            if path is None:
                continue
            self._used.add(path)
            try:
                img = Image.open(path)
                img.load()
            except Exception as exc:
                log.warning("unreadable cached face %s: %s", path.name, exc)
                continue
            ref = encode_reference(img)
            if ref.get("ok"):
                return img, ref
            log.info("skipping %s — %s", path.name, ref.get("error"))
        return None


# ── enrolment ───────────────────────────────────────────────────────────────

def _enrol(session, suspect: Suspect, supply: FaceSupply) -> bool:
    taken = supply.take()
    if taken is None:
        log.warning("no usable portrait available for %s", suspect.full_name)
        return False
    img, ref = taken
    thumb = face_db.crop_thumb(img, ref["bounding_box"])
    added = face_db.add_template(session, suspect, encoding=ref["encoding"],
                                 quality=ref["quality"],
                                 source="synthetic reference (StyleGAN)",
                                 thumb=thumb)
    if not added.get("ok"):
        log.warning("could not enrol %s: %s", suspect.full_name, added.get("error"))
        return False
    log.info("enrolled %-22s quality=%s", suspect.full_name, ref["quality"]["score"])
    return True


def seed(*, offline: bool = False) -> dict:
    supply = FaceSupply(offline=offline)
    augmented = created = enrolled = 0

    with session_scope() as s:
        # Pass 1 — complete the records suspect_seed.py left half-finished.
        for name, extra in _AUGMENT.items():
            row = s.exec(select(Suspect)
                         .where(col(Suspect.full_name) == name)).first()
            if row is None:
                continue
            changed = False
            for field, value in extra.items():
                if not getattr(row, field, None):
                    setattr(row, field, value)
                    changed = True
            if changed:
                if _SYNTHETIC_NOTE not in (row.notes or ""):
                    row.notes = ((row.notes or "") + " " + _SYNTHETIC_NOTE).strip()
                row.updated_at = utcnow()
                s.add(row)
                s.commit()
                augmented += 1
            if not (row.face_templates or []):
                if _enrol(s, row, supply):
                    enrolled += 1

        # Pass 2 — the new records.
        for template in _NEW:
            data = dict(template)
            extra_note = data.pop("notes_extra", "")
            name = data["full_name"]
            row = s.exec(select(Suspect)
                         .where(col(Suspect.full_name) == name)).first()
            if row is None:
                data["notes"] = (extra_note + " " if extra_note else "") + _DEMO_NOTE
                row = Suspect(**data, source=DEMO_SOURCE)
                s.add(row)
                s.commit()
                s.refresh(row)
                created += 1
            if not (row.face_templates or []):
                if _enrol(s, row, supply):
                    enrolled += 1

    return {"augmented": augmented, "created": created, "enrolled": enrolled}


def reset() -> dict:
    """Undo this script: delete its own records, un-enrol what it added.

    The four `source="seed"` rows are *not* deleted — they predate this script
    and suspect_seed.py owns them. Their synthetic templates are stripped,
    which returns them to the unenrolled state they ship in. Analyst-created
    records are never touched.
    """
    deleted = stripped = 0
    with session_scope() as s:
        for row in s.exec(select(Suspect)
                          .where(col(Suspect.source) == DEMO_SOURCE)).all():
            s.delete(row)
            deleted += 1
        s.commit()

        for name in _AUGMENT:
            row = s.exec(select(Suspect)
                         .where(col(Suspect.full_name) == name)).first()
            if row is None or not (row.face_templates or []):
                continue
            kept = [t for t in row.face_templates
                    if "StyleGAN" not in (t.get("source") or "")]
            if len(kept) != len(row.face_templates):
                row.face_templates = kept
                if not kept:
                    row.photo_thumb = ""
                row.updated_at = utcnow()
                s.add(row)
                stripped += 1
        s.commit()
    return {"deleted": deleted, "unenrolled": stripped}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Seed the suspect registry with synthetic faces and full "
                    "classifications, so identification is demonstrable.")
    parser.add_argument("--reset", action="store_true",
                        help="remove the records this script created and "
                             "un-enrol the photos it added")
    parser.add_argument("--offline", action="store_true",
                        help="use only portraits already cached in "
                             ".demo_faces/; never reach the network")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if args.reset:
        result = reset()
        print(f"removed {result['deleted']} demo record(s), "
              f"un-enrolled {result['unenrolled']} seeded record(s)")
        return

    result = seed(offline=args.offline)
    print(f"augmented {result['augmented']} seeded record(s), "
          f"created {result['created']} new record(s), "
          f"enrolled {result['enrolled']} reference photo(s)")
    print(f"portrait cache: {_CACHE_DIR}")


if __name__ == "__main__":
    main()
