"""Add fields from main

Revision ID: 5ec51895864f
Revises: c02306f56d1f
Create Date: 2026-07-18 15:24:56.619651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec51895864f'
down_revision: Union[str, Sequence[str], None] = 'c02306f56d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('media_urls', sa.JSON(), nullable=True))
    op.add_column('post', sa.Column('fact_check', sa.JSON(), nullable=True))
    op.add_column('post', sa.Column('evidence_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'evidence_report')
    op.drop_column('post', 'fact_check')
    op.drop_column('post', 'media_urls')
    # ### end Alembic commands ###
